[package]
name = "kos"
version = "0.1.0"
authors = ["tamiyo"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
register = "0.5.1"
cortex-a = "3.0.4"